//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainsOfTomorrow.MindWave.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainsOfTomorrow.MindWave.Core.Properties.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na conexão..
        /// </summary>
        internal static string ConnectionFailure {
            get {
                return ResourceManager.GetString("ConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALHA APÓS CONEXÃO ESTABELECIDA.
        /// </summary>
        internal static string ConnectionFailureError {
            get {
                return ResourceManager.GetString("ConnectionFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALHA NO SOCKET DE COMUNICAÇÃO.
        /// </summary>
        internal static string ConnectSocketError {
            get {
                return ResourceManager.GetString("ConnectSocketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCORREU UMA FALHA GENÉRICA.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCESSO.
        /// </summary>
        internal static string GenericSuccess {
            get {
                return ResourceManager.GetString("GenericSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PROPRIEDADE {0} NÃO REPRESENTA UM IP VALIDO.
        /// </summary>
        internal static string IpConfigurationError {
            get {
                return ResourceManager.GetString("IpConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PROPRIEDADE {0} NÃO REPRESENTA UMA PORTA VALIDO.
        /// </summary>
        internal static string PortConfigurationError {
            get {
                return ResourceManager.GetString("PortConfigurationError", resourceCulture);
            }
        }
    }
}
